### ISSUE TITLE
where can get the dataset?

### ISSUE THREAD

**Issue by Xuanyuanbingxue** [0Kirby/GenderRecognition#1]
Hello, thank you for your code and report. 
But when I prepare to download the dataset, the website cannot afford the dataset to uninvited custom.  So can you send the dataset to me?
Thanks very much.

**Comment by 0Kirby** [comment]
OK, I have uploaded the dataset to a cloud drive.
[Download Link](https://0kirby.lanzoux.com/b00zzo7xa)  
Please download all the two files, then unzip them into a same directory.

**Comment by Xuanyuanbingxue** [comment]
> OK, I have uploaded the dataset to a cloud drive.
> [Download Link](https://0kirby.lanzouu.com/b00zzo7xa)
> Please download all the two files, then unzip them into a same directory.

thank you very much，it help me a lot~
